### ISSUE TITLE
Tenant specific IOptions<T> and middleware ctors dont work, workaround

### ISSUE THREAD

**Issue by halllo** [DanielRBowen/SimpleMultiTenant#1]
Hi Daniel.

I just wanted to reach out to you and let you know that I am also working on multi tenancy in ASP.NET core (https://github.com/halllo/IdentityServerExperiments/tree/dev/IdentityServer/MultiTenancy).
We both use the same source (https://michael-mckenna.com/multi-tenancy-compatibility-dot-net-core-three). However, there is a problem (he does not mention it) with tenant specific options in regards to middlewares.
If the middleware requires an IOptions<T> in its constructor and because middleware constructors are invoked before there is any tenant context from requests, those middlewares need to be wrapped and the IOptions<T> should be taken from the context.RequestServices (tenant container) instead. Unfortunately I didn't find any other way to get the CookiePolicyMiddleware to work in tenant context (https://github.com/halllo/IdentityServerExperiments/blob/dev/IdentityServer/MultiTenancy/MultiTenantCookiePolicyMiddleware.cs).

I hope this saves you some time, if you plan to add a cookie policy :)
Feel free to reach out to me on https://twitter.com/halllo, especially if you find more 'interesting things'. We should build a simple library out of this, since both saaskit and dotnettency are not up to date on 3.1 :(

Kindest regards
Manuel

**Comment by DanielRBowen** [comment]
Thank you Manuel,

However, my multi-tenant implementation does not use autofac anymore or IOptions. It only uses the first part of [Michael's blog](https://michael-mckenna.com/multi-tenant-asp-dot-net-core-application-tenant-resolution/) to resolve the tenant. I deleted all of the autofac stuff including the IOptions. My implementation just injects a tenantsDbContext into the applicationDbContext and the constructor builds the ContextDbOptions for the context with the correct tenant connection string from the resolved tenant name.

I do not plan on making a simple library because I think it is simple enough with the right understanding to make a multi-tenant implementation of a web app with it tailored to the project and don't think it is worth the effort to make a library.

I wish you the best in your projects,
Daniel
